### ISSUE TITLE
More improvements for experimental implementation

### ISSUE THREAD

**Issue by strombw** [Ambrosys/glyph#18]
- [x] Smart termination of constant optimization. If it does not look like the fitness is improving fast enough (compared to the best fitness), give up.
- [x] Implement structural constants
- [x] Constraints based on simplified expressions (do not evaluate zero or inf functions)
- [x] Send an entire generation to the experiment to be evaluated at once (returns vector of fitness values).
- [x] Asynchronous communication in glyph_remote for sending/receiving functions and fitness values

**Comment by markusabel** [comment]
Stupid question: what are structural constants?

**Comment by strombw** [comment]
It is an alternative to constant optimization, wherein constants are
allowed to have sub-trees. The constant value is then calculated using the
structure of the sub-tree (ratio of the number of nodes on the two sides of
the first branch I think). Markus Quade can point you to a paper and
correct me if I've explained this incorrectly.

We hope it allows us to avoid constant optimization but still have flexible
constant values in the experimental implementation we are working on.

Cheers,
Ben

**Comment by Ohjeah** [comment]
http://link.springer.com/chapter/10.1007/978-3-642-40669-0_12 this is the paper

**Comment by Ohjeah** [comment]
* async is WIP (see https://github.com/Ohjeah/glyph/commit/ffa0db4fdca9cef31a72b35a1f7eef78733f5b0c)
* structural constants are implemented (https://github.com/Ohjeah/glyph/commit/b9b5099edbc7980c444de84c66c9acc41c36bbc3) tinkering on the api in glyph remote now

**Comment by Ohjeah** [comment]
I implemented an experimental stopping criteria in https://github.com/Ohjeah/glyph/commit/3950cba1f218df728ba8b2ef28b1658b49629aab

You can use this to wrap around the method used in scipy.optimize.minimize. If improvement rate (delta f/ function evaluations) is smaller than a user specified quantile q_p constant optimization will be stopped. This cuts away about p% of the total function evaluations and thus experiments.
