### ISSUE TITLE
Examples are broken due to a class that was moved

### ISSUE THREAD

**Issue by aldanor** [Ambrosys/glyph#62]
Looks like `AExpressionTree` was moved from `glyph.gp` to `glyph.gp.individual` so some examples cannot start up and fail due to an import error.

Would it makes sense to at least import the examples files in the test suite to ensure they are up to date?

**Comment by aldanor** [comment]
In `lorenz.py`, if you fix the import it further fails with `load_config() got an unexpected keyword argument 'default_level'`.

**Comment by Ohjeah** [comment]
Thanks for the report. 

I will fix this bug and add the control examples to the [integration test which runs all examples.](https://github.com/Ambrosys/glyph/blob/master/tests/integration_test/test_examples.py#L41)
