### ISSUE TITLE
Question: How to make use of optimized constants?

### ISSUE THREAD

**Issue by PGijsbers** [Ambrosys/glyph#70]
The package description mentions "interfacing constant optimization to scipy.optimize", but we have trouble finding any further documentation on this. How can we make sure our constants are optimized?

**Comment by Ohjeah** [comment]
Have a look at this [example](https://github.com/Ambrosys/glyph/blob/master/examples/symbolic_regression/symbolic_regression.py#L37). The api docs of the constant optimization function can be found [here](https://glyph.readthedocs.io/en/latest/dev/api/glyph/#glyph.assessment.const_opt).
