### ISSUE TITLE
glyph.utils.numeric SlowConversionTerminator not working properly ?

### ISSUE THREAD

**Issue by Riuza-c-137** [Ambrosys/glyph#73]
## Summary

Hi, as I'm about to use pyglyph for a science projet in school, I am currently going through your code and I think I found something wrong with the SlowConversionTerminator class. Sorry in advance if I'm not using github correctly, I'm new to it, but the concerned code si pretty short, so I hope to be clear enough. 

If my understanding is correct, the whole desired effect of using this class is to optimize some function (find the values of its variables so that the result is close to 0), and killing the optimisation process if it detects that the optimisation is too slow, hence the name of the class.

As I first read through this code, I did not understand why the variable "fev" was constantly increasing, then I tested with the following code for myself : 

![image](https://user-images.githubusercontent.com/68611178/136487024-656590a4-e069-4177-be3d-68f52546146a.png)

The function used obviously cannot be optimized, I wanted to see if it detects it, but it did not. The process on the whole, just spams the current optimisation method (hill_climb here) until maxfev is reached :  the maximum number of iteration (by default maxfev=1000 in this case).

The current if statement never could have been met (in the main loop of the class) : 
![image](https://user-images.githubusercontent.com/68611178/136487550-c582eea0-fe05-4c8a-bc07-b3a5ec3313c2.png)

As fev is constantly increasing, self.memory[fev] is always of length 1 (and self.min_stat is by default 10), and the "break early of the while loop" following this condition is never executed.

## Possible fixes

I replaced the class code with the following, and it seems to work at least for the case I was testing for.

![image](https://user-images.githubusercontent.com/68611178/136486080-9ffb7e45-3190-4f60-a25a-19da4a42c770.png)

**Comment by Ohjeah** [comment]
Hey @Riuza-c-137 

you are right, the cumulated function evaluation counter `fev` and the number of evaluation per iteration step `res.nfev` are mixed up. I think it will be sufficient to replace `rev` by `res.nfev` in [L134 to L137](https://github.com/Ambrosys/glyph/blob/master/glyph/utils/numeric.py#L134-L137) (similar to your suggestion).

Would you mind submitting a pull request?

Cheers

**Comment by Riuza-c-137** [comment]
Yeah sure, i'll try my best.

Your suggestion will fix it, though I don't know why your making "memory" a dictionnary, it's not like the key (: res.nfev) will change between iterations ? But hey it works okay

**Comment by Ohjeah** [comment]
res.nfev may change depending on the optimization method
